defaults:
  - _self_
  # - training: dpo_fast
  - training: sft_recommended_dense_full
  - lr_scheduler: cosine
  - logger: wandb
  # - override hydra/launcher: submitit_slurm
seed: 42
experiment_name: ${training.sft_experiment.lora.r}_${training.sft_experiment.lora.k}_layer${training.sft_experiment.lora.layer}
# experiment_name: ${training.dpo_experiment.lora.r}_${training.dpo_experiment.lora.k}_layer${training.dpo_experiment.lora.layer}
