defaults:
  - _self_
  - training: dpo
  - lr_scheduler: cosine
  - logger: wandb
  # - override hydra/launcher: submitit_slurm
seed: 42
experiment_name: ${training.method}_${training.model}_experiment