defaults:
  - _self_
  - logger: wandb_disabled
  - evals/causal-autointerp-hh@evals.causal_autointerp_framework
  - model: topk_dpo_model

seed: 42
checkpoint_dir: adapter
experiment_name: ${evals}_eval
