method: "sft"

sft:
  enabled: True
  batch_size_train: 12
  batch_size_eval: 12
  num_epochs: 15
  gradient_checkpointing: True
  push_to_hub: False
  max_seq_length: 2048
  weight_decay: 0.001
  max_steps: 1000
  save_steps: 50
  eval_steps: 100
  lr: 1e-4
  do_eval: True
dpo:
  enabled: False