defaults:
  - model: llama_3_1b_instruct
  - training: sft
  - dataset_sft: spider
  - dataset_dpo: binarized
  - optimizer: adamw
  - experiment: lora_r_16_mlp_attn_llama
  - lr_scheduler: cosine
  - logger: wandb_disabled
  # - override hydra/launcher: submitit_slurm
seed: 42
experiment_name: ${training.method}_${model.name}_${model.version}_${model.size}_${experiment.size}
