defaults:
  - quantization: 4bit
  - _self_
name: "gemma"
version: 2.0
size: "2B"
type: dpo_model
k: 2
r: 512
base_model: "/scratch/network/ssd/marek/lora_interp/cache/tempartefacts/google/gemma-2-2b_sft"
model_it_name: "google/gemma-2-2b-it"
adapter_checkpoint_dir: "/scratch/network/ssd/marek/lora_interp/models/dpo/google/gemma-2-2b/google-gemma-2-2b_topk_dpo_20250813_112006_3797c9bd/final_adapter"
train_steps: 7500