name: "gemma"
version: 2.0
size: "2B"
type: dpo_model
k: 32
r: 4096
base_model: "/scratch/network/ssd/marek/lora_interp/cache/tempartefacts/gemma-2-2b_sft"
model_it_name: "google/gemma-2-2b-it"
adapter_checkpoint_dir: "/scratch/network/ssd/marek/lora_interp/cache/tempartefacts/final_adapter_4096"
train_steps: 5000